### ISSUE TITLE
Transfer http code as destination server

### ISSUE THREAD

**Issue by WoodySlum** [jenssegers/php-proxy#35]
Hi, I have custom http codes (can be 2XX, 5XX, 6XX, ...) in the destination server.
I would like to keep the http code exactly as destination server ; on proxy side I get always 500 errors with this stack trace :
```
[09-Jan-2016 11:30:55 Europe/Berlin] PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://mydomain.com/BLAHBLAH/services/` resulted in a `417 Expectation Failed` response:
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "htt (truncated...)
' in /Library/WebServer/Documents/BLAHBLAH/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107
Stack trace:
#0 /Library/WebServer/Documents/BLAHBLAH/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(Zend\Diactoros\ServerRequest), Object(GuzzleHttp\Psr7\Response))
#1 /Library/WebServer/Documents/BLAHBLAH/vendor/guzzlehttp/promises/src/Promise.php(199): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /Library/WebServer/Documents/BLAHBLAH/vendor/guzzlehttp/promises/src/Promise.php(152): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /Library/WebSe in /Library/WebServer/Documents/BLAHBLAH/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 107
```

Could it be possible ?

**Comment by WoodySlum** [comment]
Here is how to fix my issue :

```
$guzzle = new GuzzleHttp\Client(array('exceptions'=>false, 'expect' => false));
```
