### ISSUE TITLE
EmitterException: Output has been emitted previously

### ISSUE THREAD

**Issue by kishieel** [jenssegers/php-proxy#89]
PHP Version: 7.3.23
Server: Server: Apache/2.4.25 (Debian)
Stack: Pure PHP ( only jenssegers/php-proxy installed )

Since I added Let's Encrypt certificate to my domain I got error:
```
Fatal error: Uncaught Laminas\HttpHandlerRunner\Exception\EmitterException: Output has been emitted previously; cannot emit response in /usr/home/abcd/domains/example.com/public_html/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php:24
Stack trace:
#0 /usr/home/abcd/domains/example.com/public_html/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitterTrait.php(40): Laminas\HttpHandlerRunner\Exception\EmitterException::forOutputSent()
#1 /usr/home/abcd/domains/example.com/public_html/vendor/laminas/laminas-httphandlerrunner/src/Emitter/SapiEmitter.php(27): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->assertNoPreviousOutput()
#2 /usr/home/abcd/domains/example.coml/public_html/index.php(56): Laminas\HttpHandlerRunner\Emitter\SapiEmitter->emit(Object(GuzzleHttp\Psr7\Response))
#3 {main}
thrown in /usr/home/abcd/domains/example.com/public_html/vendor/laminas/laminas-httphandlerrunner/src/Exception/EmitterException.php on line 24
``` 

Still working with HTTP.

**Comment by Kazzaky** [comment]
i have same issue

**Comment by filisko** [comment]
Me too
